[env:esp01]
platform = espressif8266
board = esp01
framework = arduino
upload_speed = 115200
monitor_speed = 115200
lib_extra_dirs = .
upload_port = 192.168.4.1

[env:esp01_ota]
platform = espressif8266
board = esp01
framework = arduino
upload_speed = 115200
monitor_speed = 115200
upload_protocol = espota
lib_extra_dirs = .
