#ifndef PROTOCOLSETTINGS_H
#define PROTOCOLSETTINGS_H

#define ARTNET_PORT 6454
#define ARTNET_MAX_BUFFER 530
#define ARTNET_DMX_START_LOC 18
#define ARTNET_ID "Art-Net\0"

#define DMX_MAX_OUTPUTS 4
#define DMX_MAX_BUFFER 512
#define DMX_RDM_STARTCODE 0xCC

#endif
